metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.1.110, mac: 'ac:e2:d3:0e:d8:63', disk: sda, network_interface: eth0}
        metal1: {ansible_host: 192.168.1.111, mac: 'ac:e2:d3:11:33:17', disk: sda, network_interface: eth0}
    workers:
      hosts:
        metal2: {ansible_host: 192.168.1.112, mac: '10:e7:c6:00:28:35', disk: sda, network_interface: eth0}
