apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: matrix-secrets
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: matrix-secrets
  data:
    - secretKey: MATRIX_REGISTRATION_SECRET
      remoteRef:
        key: /matrix/registration
        property: secret
    - secretKey: MATRIX_CAPTCHA_SITE_KEY
      remoteRef:
        key: /matrix/registration/captcha
        property: site_key
    - secretKey: MATRIX_CAPTCHA_SITE_SECRET
      remoteRef:
        key: /matrix/registration/captcha
        property: secret_key