gitea:
  ingress:
    apiVersion: networking.k8s.io/v1
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      hajimari.io/appName: Gitea
      hajimari.io/icon: git
    hosts:
      - host: &host git.timoriski.fi
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: gitea-tls-certificate
        hosts:
          - *host
  gitea:
    admin:
      existingSecret: gitea-admin-secret
    config:
      server:
        LANDING_PAGE: explore
        ROOT_URL: https://git.timoriski.fi
      webhook:
        ALLOWED_HOST_LIST: private
  persistence:
    storageClass: longhorn
  postgresql:
    enabled: true
    auth:
      postgresPassword: "<path:secret/data/db/passwords#user-postgres>"
      username: gitea
      password: "<path:secret/data/db/passwords/#user-gitea>"
      database: gitea
    persistence:
      storageClass: longhorn
