renovate:
  cronjob:
    schedule: '0 9 * * 0'  # At 09:00 every Sunday
  renovate:
    config: |
      {
        "platform": "gitea",
        "endpoint": "https://git.timoriski.fi/api/v1",
        "token": "<path:secret/data/gitea/renovate#token>",
        "gitAuthor": "Renovate Bot <bot@renovateapp.com>",
        "autodiscover": true,
        "binarySource": "docker"
      }
  existingSecret: renovate-secret
  dind:
    enabled: true
