renovate:
  cronjob:
    schedule: '0 9 * * *'  # Everyday at 09:00
  renovate:
    config: |
      {
        "platform": "gitea",
        "endpoint": "https://git.timoriski.fi/api/v1",
        "gitAuthor": "Renovate Bot <bot@renovateapp.com>",
        "autodiscover": true,
        "binarySource": "docker"
      }
  existingSecret: renovate-secret
  dind:
    enabled: true
