---
- name: Set net.core.rmem_max=2500000
  # Fixes "failed to sufficiently increase receive buffer size" issue with
  # cloudflared.
  #
  # See:
  #  - https://github.com/cloudflare/cloudflared/issues/632
  #  - https://github.com/quic-go/quic-go/wiki/UDP-Receive-Buffer-Size
  ansible.posix.sysctl:
    name: net.core.rmem_max
    value: "2500000"
    state: present
    reload: true
