element-web:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/target: "homelab-tunnel.timoriski.fi"
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
      hajimari.io/appName: Chat
      hajimari.io/icon: chat
    hosts:
      - host: &frontend_host chat.timoriski.fi
        paths: 
          - /
    tls:
      - secretName: element-tls-certificate
        hosts:
          - *frontend_host
  configjson:
    default_server_config:
      m.homeserver:
        base_url: "https://matrix.timoriski.fi"
        server_name: "riski"
      m.identity_server:
        base_url: "https://vector.im"

dendrite:
  polylithEnabled: false
  global:
    server_name: &backend_host matrix.timoriski.fi
    metrics:
      enabled: true
  clientapi:
    config:
      registration_disabled: true
      registration_shared_secret: riskimatriisi
      captcha:
        enabled: "false"
  database:
    max_open_conns: 100
    max_idle_conns: 2
    conn_max_lifetime: -1
  persistence:
    jetstream:
      enabled: true
    media:
      enabled: true
  nats:
    enabled: true
    nats:
      jetstream:
        enabled: true
  postgresql:
    enabled: true
    auth:
      database: dendrite
      username: dendrite
      password: dendrite
    persistence:
      enabled: true
      storageClass: longhorn
      accessModes:
        - ReadWriteOnce
      size: 5Gi
  tls_secret:
    enabled: true
    existingSecret: dendrite-tls-certificate
  ingress:
    main: 
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/target: "homelab-tunnel.timoriski.fi"
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        nginx.ingress.kubernetes.io/proxy-body-size: 32m
        hajimari.io/enable: 'false'
      hosts:
        - host: *backend_host
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: dendrite-tls-certificate
          hosts:
            - *backend_host
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true