apiVersion: v1
kind: ConfigMap
metadata:
  name: generate-secrets-source
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
{{ .Files.Get "files/generate-secrets/config.yaml" | indent 4 }}
  go.mod: |
{{ .Files.Get "files/generate-secrets/go.mod" | indent 4 }}
  go.sum: |
{{ .Files.Get "files/generate-secrets/go.sum" | indent 4 }}
  main.go: |
{{ .Files.Get "files/generate-secrets/main.go" | indent 4 }}
